package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Gramatika generated by hbm2java
 */
@Entity
@Table(name="Gramatika"
    ,catalog="let1"
)
public class Gramatika  implements java.io.Serializable {


     private Integer id;
     private String ispravnaRec;

    public Gramatika() {
    }

    public Gramatika(String ispravnaRec) {
       this.ispravnaRec = ispravnaRec;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ispravnaRec", length=45)
    public String getIspravnaRec() {
        return this.ispravnaRec;
    }
    
    public void setIspravnaRec(String ispravnaRec) {
        this.ispravnaRec = ispravnaRec;
    }




}


