package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IgraDana generated by hbm2java
 */
@Entity
@Table(name="IgraDana"
    ,catalog="let1"
)
public class IgraDana  implements java.io.Serializable {


     private Integer id;
     private Date start;
     private Integer idasocijacija;
     private Integer idspojnice;
     private Integer odigrano;

    public IgraDana() {
    }

    public IgraDana(Date start, Integer idasocijacija, Integer idspojnice, Integer odigrano) {
       this.start = start;
       this.idasocijacija = idasocijacija;
       this.idspojnice = idspojnice;
       this.odigrano = odigrano;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="Start", length=0)
    public Date getStart() {
        return this.start;
    }
    
    public void setStart(Date start) {
        this.start = start;
    }

    
    @Column(name="IDasocijacija")
    public Integer getIdasocijacija() {
        return this.idasocijacija;
    }
    
    public void setIdasocijacija(Integer idasocijacija) {
        this.idasocijacija = idasocijacija;
    }

    
    @Column(name="IDspojnice")
    public Integer getIdspojnice() {
        return this.idspojnice;
    }
    
    public void setIdspojnice(Integer idspojnice) {
        this.idspojnice = idspojnice;
    }

    
    @Column(name="odigrano")
    public Integer getOdigrano() {
        return this.odigrano;
    }
    
    public void setOdigrano(Integer odigrano) {
        this.odigrano = odigrano;
    }




}


