package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Imagen generated by hbm2java
 */
@Entity
@Table(name="imagen"
    ,catalog="let1"
)
public class Imagen  implements java.io.Serializable {


     private Integer id;
     private byte[] img;
     private String identifikatorAviona;

    public Imagen() {
    }

    public Imagen(byte[] img, String identifikatorAviona) {
       this.img = img;
       this.identifikatorAviona = identifikatorAviona;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="img")
    public byte[] getImg() {
        return this.img;
    }
    
    public void setImg(byte[] img) {
        this.img = img;
    }

    
    @Column(name="identifikatorAviona", length=45)
    public String getIdentifikatorAviona() {
        return this.identifikatorAviona;
    }
    
    public void setIdentifikatorAviona(String identifikatorAviona) {
        this.identifikatorAviona = identifikatorAviona;
    }




}


