package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OdigranaIgraDana generated by hbm2java
 */
@Entity
@Table(name="OdigranaIgraDana"
    ,catalog="let1"
)
public class OdigranaIgraDana  implements java.io.Serializable {


     private Integer id;
     private String username;
     private Integer odigrano;
     private Date datum;
     private Integer bodovi;

    public OdigranaIgraDana() {
    }

    public OdigranaIgraDana(String username, Integer odigrano, Date datum, Integer bodovi) {
       this.username = username;
       this.odigrano = odigrano;
       this.datum = datum;
       this.bodovi = bodovi;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="odigrano")
    public Integer getOdigrano() {
        return this.odigrano;
    }
    
    public void setOdigrano(Integer odigrano) {
        this.odigrano = odigrano;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datum", length=0)
    public Date getDatum() {
        return this.datum;
    }
    
    public void setDatum(Date datum) {
        this.datum = datum;
    }

    
    @Column(name="bodovi")
    public Integer getBodovi() {
        return this.bodovi;
    }
    
    public void setBodovi(Integer bodovi) {
        this.bodovi = bodovi;
    }




}


