package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pobednici generated by hbm2java
 */
@Entity
@Table(name="Pobednici"
    ,catalog="let1"
)
public class Pobednici  implements java.io.Serializable {


     private Integer id;
     private String username;
     private Integer poeni;
     private Date datumIgranja;

    public Pobednici() {
    }

    public Pobednici(String username, Integer poeni, Date datumIgranja) {
       this.username = username;
       this.poeni = poeni;
       this.datumIgranja = datumIgranja;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="username", length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="poeni")
    public Integer getPoeni() {
        return this.poeni;
    }
    
    public void setPoeni(Integer poeni) {
        this.poeni = poeni;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="datumIgranja", length=0)
    public Date getDatumIgranja() {
        return this.datumIgranja;
    }
    
    public void setDatumIgranja(Date datumIgranja) {
        this.datumIgranja = datumIgranja;
    }




}


