package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PojmoviSpojnice generated by hbm2java
 */
@Entity
@Table(name="PojmoviSpojnice"
    ,catalog="let1"
)
public class PojmoviSpojnice  implements java.io.Serializable {


     private Integer id;
     private String polje11;
     private String polje12;
     private String polje21;
     private String polje22;
     private String polje31;
     private String polje32;
     private String polje41;
     private String polje42;
     private String polje51;
     private String polje52;
     private String polje61;
     private String polje62;
     private String polje71;
     private String polje72;
     private String polje81;
     private String polje82;
     private String polje91;
     private String polje92;
     private String polje101;
     private String polje102;

    public PojmoviSpojnice() {
    }

    public PojmoviSpojnice(String polje11, String polje12, String polje21, String polje22, String polje31, String polje32, String polje41, String polje42, String polje51, String polje52, String polje61, String polje62, String polje71, String polje72, String polje81, String polje82, String polje91, String polje92, String polje101, String polje102) {
       this.polje11 = polje11;
       this.polje12 = polje12;
       this.polje21 = polje21;
       this.polje22 = polje22;
       this.polje31 = polje31;
       this.polje32 = polje32;
       this.polje41 = polje41;
       this.polje42 = polje42;
       this.polje51 = polje51;
       this.polje52 = polje52;
       this.polje61 = polje61;
       this.polje62 = polje62;
       this.polje71 = polje71;
       this.polje72 = polje72;
       this.polje81 = polje81;
       this.polje82 = polje82;
       this.polje91 = polje91;
       this.polje92 = polje92;
       this.polje101 = polje101;
       this.polje102 = polje102;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="polje11", length=45)
    public String getPolje11() {
        return this.polje11;
    }
    
    public void setPolje11(String polje11) {
        this.polje11 = polje11;
    }

    
    @Column(name="polje12", length=45)
    public String getPolje12() {
        return this.polje12;
    }
    
    public void setPolje12(String polje12) {
        this.polje12 = polje12;
    }

    
    @Column(name="polje21", length=45)
    public String getPolje21() {
        return this.polje21;
    }
    
    public void setPolje21(String polje21) {
        this.polje21 = polje21;
    }

    
    @Column(name="polje22", length=45)
    public String getPolje22() {
        return this.polje22;
    }
    
    public void setPolje22(String polje22) {
        this.polje22 = polje22;
    }

    
    @Column(name="polje31", length=45)
    public String getPolje31() {
        return this.polje31;
    }
    
    public void setPolje31(String polje31) {
        this.polje31 = polje31;
    }

    
    @Column(name="polje32", length=45)
    public String getPolje32() {
        return this.polje32;
    }
    
    public void setPolje32(String polje32) {
        this.polje32 = polje32;
    }

    
    @Column(name="polje41", length=45)
    public String getPolje41() {
        return this.polje41;
    }
    
    public void setPolje41(String polje41) {
        this.polje41 = polje41;
    }

    
    @Column(name="polje42", length=45)
    public String getPolje42() {
        return this.polje42;
    }
    
    public void setPolje42(String polje42) {
        this.polje42 = polje42;
    }

    
    @Column(name="polje51", length=45)
    public String getPolje51() {
        return this.polje51;
    }
    
    public void setPolje51(String polje51) {
        this.polje51 = polje51;
    }

    
    @Column(name="polje52", length=45)
    public String getPolje52() {
        return this.polje52;
    }
    
    public void setPolje52(String polje52) {
        this.polje52 = polje52;
    }

    
    @Column(name="polje61", length=45)
    public String getPolje61() {
        return this.polje61;
    }
    
    public void setPolje61(String polje61) {
        this.polje61 = polje61;
    }

    
    @Column(name="polje62", length=45)
    public String getPolje62() {
        return this.polje62;
    }
    
    public void setPolje62(String polje62) {
        this.polje62 = polje62;
    }

    
    @Column(name="polje71", length=45)
    public String getPolje71() {
        return this.polje71;
    }
    
    public void setPolje71(String polje71) {
        this.polje71 = polje71;
    }

    
    @Column(name="polje72", length=45)
    public String getPolje72() {
        return this.polje72;
    }
    
    public void setPolje72(String polje72) {
        this.polje72 = polje72;
    }

    
    @Column(name="polje81", length=45)
    public String getPolje81() {
        return this.polje81;
    }
    
    public void setPolje81(String polje81) {
        this.polje81 = polje81;
    }

    
    @Column(name="polje82", length=45)
    public String getPolje82() {
        return this.polje82;
    }
    
    public void setPolje82(String polje82) {
        this.polje82 = polje82;
    }

    
    @Column(name="polje91", length=45)
    public String getPolje91() {
        return this.polje91;
    }
    
    public void setPolje91(String polje91) {
        this.polje91 = polje91;
    }

    
    @Column(name="polje92", length=45)
    public String getPolje92() {
        return this.polje92;
    }
    
    public void setPolje92(String polje92) {
        this.polje92 = polje92;
    }

    
    @Column(name="polje101", length=45)
    public String getPolje101() {
        return this.polje101;
    }
    
    public void setPolje101(String polje101) {
        this.polje101 = polje101;
    }

    
    @Column(name="polje102", length=45)
    public String getPolje102() {
        return this.polje102;
    }
    
    public void setPolje102(String polje102) {
        this.polje102 = polje102;
    }




}


