package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PojmoviAsocijacije generated by hbm2java
 */
@Entity
@Table(name="PojmoviAsocijacije"
    ,catalog="let1"
)
public class PojmoviAsocijacije  implements java.io.Serializable {


     private Integer id;
     private String a1;
     private String a2;
     private String a3;
     private String a4;
     private String b1;
     private String b2;
     private String b3;
     private String b4;
     private String v1;
     private String v2;
     private String v3;
     private String v4;
     private String g1;
     private String g2;
     private String g3;
     private String g4;
     private String kolA;
     private String kolB;
     private String kolV;
     private String kolG;
     private String konacno;
     private Integer sifra;

    public PojmoviAsocijacije() {
    }

    public PojmoviAsocijacije(String a1, String a2, String a3, String a4, String b1, String b2, String b3, String b4, String v1, String v2, String v3, String v4, String g1, String g2, String g3, String g4, String kolA, String kolB, String kolV, String kolG, String konacno, Integer sifra) {
       this.a1 = a1;
       this.a2 = a2;
       this.a3 = a3;
       this.a4 = a4;
       this.b1 = b1;
       this.b2 = b2;
       this.b3 = b3;
       this.b4 = b4;
       this.v1 = v1;
       this.v2 = v2;
       this.v3 = v3;
       this.v4 = v4;
       this.g1 = g1;
       this.g2 = g2;
       this.g3 = g3;
       this.g4 = g4;
       this.kolA = kolA;
       this.kolB = kolB;
       this.kolV = kolV;
       this.kolG = kolG;
       this.konacno = konacno;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="A1", length=45)
    public String getA1() {
        return this.a1;
    }
    
    public void setA1(String a1) {
        this.a1 = a1;
    }

    
    @Column(name="A2", length=45)
    public String getA2() {
        return this.a2;
    }
    
    public void setA2(String a2) {
        this.a2 = a2;
    }

    
    @Column(name="A3", length=45)
    public String getA3() {
        return this.a3;
    }
    
    public void setA3(String a3) {
        this.a3 = a3;
    }

    
    @Column(name="A4", length=45)
    public String getA4() {
        return this.a4;
    }
    
    public void setA4(String a4) {
        this.a4 = a4;
    }

    
    @Column(name="B1", length=45)
    public String getB1() {
        return this.b1;
    }
    
    public void setB1(String b1) {
        this.b1 = b1;
    }

    
    @Column(name="B2", length=45)
    public String getB2() {
        return this.b2;
    }
    
    public void setB2(String b2) {
        this.b2 = b2;
    }

    
    @Column(name="B3", length=45)
    public String getB3() {
        return this.b3;
    }
    
    public void setB3(String b3) {
        this.b3 = b3;
    }

    
    @Column(name="B4", length=45)
    public String getB4() {
        return this.b4;
    }
    
    public void setB4(String b4) {
        this.b4 = b4;
    }

    
    @Column(name="V1", length=45)
    public String getV1() {
        return this.v1;
    }
    
    public void setV1(String v1) {
        this.v1 = v1;
    }

    
    @Column(name="V2", length=45)
    public String getV2() {
        return this.v2;
    }
    
    public void setV2(String v2) {
        this.v2 = v2;
    }

    
    @Column(name="V3", length=45)
    public String getV3() {
        return this.v3;
    }
    
    public void setV3(String v3) {
        this.v3 = v3;
    }

    
    @Column(name="V4", length=45)
    public String getV4() {
        return this.v4;
    }
    
    public void setV4(String v4) {
        this.v4 = v4;
    }

    
    @Column(name="G1", length=45)
    public String getG1() {
        return this.g1;
    }
    
    public void setG1(String g1) {
        this.g1 = g1;
    }

    
    @Column(name="G2", length=45)
    public String getG2() {
        return this.g2;
    }
    
    public void setG2(String g2) {
        this.g2 = g2;
    }

    
    @Column(name="G3", length=45)
    public String getG3() {
        return this.g3;
    }
    
    public void setG3(String g3) {
        this.g3 = g3;
    }

    
    @Column(name="G4", length=20)
    public String getG4() {
        return this.g4;
    }
    
    public void setG4(String g4) {
        this.g4 = g4;
    }

    
    @Column(name="kolA", length=20)
    public String getKolA() {
        return this.kolA;
    }
    
    public void setKolA(String kolA) {
        this.kolA = kolA;
    }

    
    @Column(name="kolB", length=20)
    public String getKolB() {
        return this.kolB;
    }
    
    public void setKolB(String kolB) {
        this.kolB = kolB;
    }

    
    @Column(name="kolV", length=20)
    public String getKolV() {
        return this.kolV;
    }
    
    public void setKolV(String kolV) {
        this.kolV = kolV;
    }

    
    @Column(name="kolG", length=20)
    public String getKolG() {
        return this.kolG;
    }
    
    public void setKolG(String kolG) {
        this.kolG = kolG;
    }

    
    @Column(name="konacno", length=20)
    public String getKonacno() {
        return this.konacno;
    }
    
    public void setKonacno(String konacno) {
        this.konacno = konacno;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


