package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PredjiDalje generated by hbm2java
 */
@Entity
@Table(name="PredjiDalje"
    ,catalog="let1"
)
public class PredjiDalje  implements java.io.Serializable {


     private Integer id;
     private String plavi;
     private String crveni;
     private Integer mojBrojPlavi;
     private Integer mojBrojCrveni;
     private Integer spojnicaPlavi;
     private Integer spojnicaCrveni;
     private Integer asocijacijaPlavi;
     private Integer asocijacijaCrveni;

    public PredjiDalje() {
    }

    public PredjiDalje(String plavi, String crveni, Integer mojBrojPlavi, Integer mojBrojCrveni, Integer spojnicaPlavi, Integer spojnicaCrveni, Integer asocijacijaPlavi, Integer asocijacijaCrveni) {
       this.plavi = plavi;
       this.crveni = crveni;
       this.mojBrojPlavi = mojBrojPlavi;
       this.mojBrojCrveni = mojBrojCrveni;
       this.spojnicaPlavi = spojnicaPlavi;
       this.spojnicaCrveni = spojnicaCrveni;
       this.asocijacijaPlavi = asocijacijaPlavi;
       this.asocijacijaCrveni = asocijacijaCrveni;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="plavi", length=45)
    public String getPlavi() {
        return this.plavi;
    }
    
    public void setPlavi(String plavi) {
        this.plavi = plavi;
    }

    
    @Column(name="crveni", length=45)
    public String getCrveni() {
        return this.crveni;
    }
    
    public void setCrveni(String crveni) {
        this.crveni = crveni;
    }

    
    @Column(name="mojBrojPlavi")
    public Integer getMojBrojPlavi() {
        return this.mojBrojPlavi;
    }
    
    public void setMojBrojPlavi(Integer mojBrojPlavi) {
        this.mojBrojPlavi = mojBrojPlavi;
    }

    
    @Column(name="mojBrojCrveni")
    public Integer getMojBrojCrveni() {
        return this.mojBrojCrveni;
    }
    
    public void setMojBrojCrveni(Integer mojBrojCrveni) {
        this.mojBrojCrveni = mojBrojCrveni;
    }

    
    @Column(name="spojnicaPlavi")
    public Integer getSpojnicaPlavi() {
        return this.spojnicaPlavi;
    }
    
    public void setSpojnicaPlavi(Integer spojnicaPlavi) {
        this.spojnicaPlavi = spojnicaPlavi;
    }

    
    @Column(name="spojnicaCrveni")
    public Integer getSpojnicaCrveni() {
        return this.spojnicaCrveni;
    }
    
    public void setSpojnicaCrveni(Integer spojnicaCrveni) {
        this.spojnicaCrveni = spojnicaCrveni;
    }

    
    @Column(name="asocijacijaPlavi")
    public Integer getAsocijacijaPlavi() {
        return this.asocijacijaPlavi;
    }
    
    public void setAsocijacijaPlavi(Integer asocijacijaPlavi) {
        this.asocijacijaPlavi = asocijacijaPlavi;
    }

    
    @Column(name="asocijacijaCrveni")
    public Integer getAsocijacijaCrveni() {
        return this.asocijacijaCrveni;
    }
    
    public void setAsocijacijaCrveni(Integer asocijacijaCrveni) {
        this.asocijacijaCrveni = asocijacijaCrveni;
    }




}


