package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinonimiB generated by hbm2java
 */
@Entity
@Table(name="SinonimiB"
    ,catalog="let1"
)
public class SinonimiB  implements java.io.Serializable {


     private Integer id;
     private String kolonaB;
     private Integer sifra;

    public SinonimiB() {
    }

    public SinonimiB(String kolonaB, Integer sifra) {
       this.kolonaB = kolonaB;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="kolonaB", length=45)
    public String getKolonaB() {
        return this.kolonaB;
    }
    
    public void setKolonaB(String kolonaB) {
        this.kolonaB = kolonaB;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


