package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinonimiV generated by hbm2java
 */
@Entity
@Table(name="SinonimiV"
    ,catalog="let1"
)
public class SinonimiV  implements java.io.Serializable {


     private Integer id;
     private String kolonaV;
     private Integer sifra;

    public SinonimiV() {
    }

    public SinonimiV(String kolonaV, Integer sifra) {
       this.kolonaV = kolonaV;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="kolonaV", length=45)
    public String getKolonaV() {
        return this.kolonaV;
    }
    
    public void setKolonaV(String kolonaV) {
        this.kolonaV = kolonaV;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


