package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinonimiKonacno generated by hbm2java
 */
@Entity
@Table(name="SinonimiKonacno"
    ,catalog="let1"
)
public class SinonimiKonacno  implements java.io.Serializable {


     private Integer id;
     private String konacno;
     private Integer sifra;

    public SinonimiKonacno() {
    }

    public SinonimiKonacno(String konacno, Integer sifra) {
       this.konacno = konacno;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="konacno", length=45)
    public String getKonacno() {
        return this.konacno;
    }
    
    public void setKonacno(String konacno) {
        this.konacno = konacno;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


