package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinonimiG generated by hbm2java
 */
@Entity
@Table(name="SinonimiG"
    ,catalog="let1"
)
public class SinonimiG  implements java.io.Serializable {


     private Integer id;
     private String kolonaG;
     private Integer sifra;

    public SinonimiG() {
    }

    public SinonimiG(String kolonaG, Integer sifra) {
       this.kolonaG = kolonaG;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="kolonaG", length=45)
    public String getKolonaG() {
        return this.kolonaG;
    }
    
    public void setKolonaG(String kolonaG) {
        this.kolonaG = kolonaG;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


