package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SinonimiA generated by hbm2java
 */
@Entity
@Table(name="SinonimiA"
    ,catalog="let1"
)
public class SinonimiA  implements java.io.Serializable {


     private Integer id;
     private String kolonaA;
     private Integer sifra;

    public SinonimiA() {
    }

    public SinonimiA(String kolonaA, Integer sifra) {
       this.kolonaA = kolonaA;
       this.sifra = sifra;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="kolonaA", length=45)
    public String getKolonaA() {
        return this.kolonaA;
    }
    
    public void setKolonaA(String kolonaA) {
        this.kolonaA = kolonaA;
    }

    
    @Column(name="sifra")
    public Integer getSifra() {
        return this.sifra;
    }
    
    public void setSifra(Integer sifra) {
        this.sifra = sifra;
    }




}


