package pojo;
// Generated Jul 6, 2019 6:11:43 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="User"
    ,catalog="let1"
    , uniqueConstraints = @UniqueConstraint(columnNames="Username") 
)
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String pol;
     private Date birthDay;
     private String username;
     private String password;
     private String email;
     private String prihvacenZahtev;
     private String tipKorisnika;
     private String job;

    public User() {
    }

	
    public User(String username) {
        this.username = username;
    }
    public User(String name, String surname, String pol, Date birthDay, String username, String password, String email, String prihvacenZahtev, String tipKorisnika, String job) {
       this.name = name;
       this.surname = surname;
       this.pol = pol;
       this.birthDay = birthDay;
       this.username = username;
       this.password = password;
       this.email = email;
       this.prihvacenZahtev = prihvacenZahtev;
       this.tipKorisnika = tipKorisnika;
       this.job = job;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ID", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="Name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="Surname")
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }

    
    @Column(name="Pol")
    public String getPol() {
        return this.pol;
    }
    
    public void setPol(String pol) {
        this.pol = pol;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="BirthDay", length=0)
    public Date getBirthDay() {
        return this.birthDay;
    }
    
    public void setBirthDay(Date birthDay) {
        this.birthDay = birthDay;
    }

    
    @Column(name="Username", unique=true, nullable=false, length=250)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="Password")
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="Email")
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="PrihvacenZahtev", length=45)
    public String getPrihvacenZahtev() {
        return this.prihvacenZahtev;
    }
    
    public void setPrihvacenZahtev(String prihvacenZahtev) {
        this.prihvacenZahtev = prihvacenZahtev;
    }

    
    @Column(name="TipKorisnika", length=45)
    public String getTipKorisnika() {
        return this.tipKorisnika;
    }
    
    public void setTipKorisnika(String tipKorisnika) {
        this.tipKorisnika = tipKorisnika;
    }

    
    @Column(name="Job", length=15)
    public String getJob() {
        return this.job;
    }
    
    public void setJob(String job) {
        this.job = job;
    }




}


